bolao_copa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from bolao.views import gerar_aposta, listar_pontos
from chat.views import chat_room
from django.shortcuts import redirect

def admin_index(request):
    return redirect('admin/')

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'bolao_copa.views.home', name='home'),
    url(r'^$',admin_index),
    url(r'^bolao/', include('bolao.urls')),
    url(r'^chat/', include('chat.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

def get_admin_urls(urls):
    def get_urls():
        my_urls = patterns('',
            (r'^apostas/$', admin.site.admin_view(gerar_aposta)),
            (r'^ranking/$', admin.site.admin_view(listar_pontos)),
            (r'^chat/$', admin.site.admin_view(chat_room)),
        )
        return my_urls + urls
    return get_urls

admin_urls = get_admin_urls(admin.site.get_urls())
admin.site.get_urls = admin_urls

chat/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    # Example chat room.
    url(r"room/$", views.chat_room, name="chat"),
    url(r"room/(?P<id>\d+)/$", views.window, name="jqchat_test_window"),
    url(r"room/(?P<id>\d+)/ajax/$", views.BasicAjaxHandler, name="jqchat_ajax"),
    # Second example room - adds room descriptions.
    url(r"room_with_description/(?P<id>\d+)/$", views.WindowWithDescription, name="jqchat_test_window_with_description"),
    url(r"room_with_description/(?P<id>\d+)/ajax/$", views.WindowWithDescriptionAjaxHandler, name="jqchat_test_window_with_description_ajax"),
)

chat/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from django.utils.safestring import mark_safe
from django.conf import settings

import datetime
import time

class Room(models.Model):
    """Conversations can take place in one of many rooms.

    >>> l = Room(name='Test room')
    >>> l.save()
    >>> l
    <Room: Test room>

    Note that updating 'description' auto-updates 'description_modified' when saving:

    >>> l.description_modified

    >>> l.description = 'A description'

    Note that we need to always set the 'user' attribute as a system message is generated for each change.
    >>> l.user = User.objects.get(id=1)
    >>> l.save()

    # description_modified is a unix timestamp.
    >>> m = l.description_modified
    >>> m > 0
    True

    """
    name = models.CharField(max_length=20, null=True, blank=True, help_text='Name of the room.')
    created = models.DateTimeField(editable=False)
    description = models.CharField(max_length=100, null=True, blank=True, help_text='The description of this room.')
    description_modified = models.IntegerField(null=True, editable=False, help_text='Unix timestamp when the description was created or last modified.')
    last_activity = models.IntegerField(editable=False,
                                        help_text='Last activity in the room. Stored as a Unix timestamp.')
    # Define generic relation to target object. This is optional.
    content_type = models.ForeignKey(ContentType, blank=True, null=True)
    object_id = models.PositiveIntegerField(blank=True, null=True)
    content_object = generic.GenericForeignKey()
    show = models.BooleanField(verbose_name=u'Show',default=True,
        help_text='Check to show this room.')

    def __unicode__(self):
        return u'%s' % (self.name)

    class Meta:
        ordering = ['created']

    def __init__(self, *args, **kw):
        super(Room, self).__init__(*args, **kw)
        self._init_description = self.description

    def save(self, **kw):
        # If description modified, update the timestamp field.
        if self._init_description != self.description:
            self.description_modified = time.time()
        # if last_activity is null (i.e. we are creating the room) set it to now.
        if not self.last_activity:
            self.last_activity = time.time()
        if not self.created:
            self.created = datetime.datetime.now()
        super(Room, self).save(**kw)

    @property
    def last_activity_formatted(self):
        """Return Unix timestamp, then express it as a time."""
        return display_timestamp(self.last_activity)

    @property
    def last_activity_datetime(self):
        """Convert last_activity into a datetime object (used to feed into timesince
        filter tag, ideally I should send a patch to Django to accept Unix times)"""
        return datetime.datetime.fromtimestamp(self.last_activity)

# The list of events can be customised for each project.
try:
    EVENT_CHOICES = settings.JQCHAT_EVENT_CHOICES
except:
    # Use default event list.
    EVENT_CHOICES = (
                  (1, "has changed the room's description."),
                  (2, "has joined the room."),
                  (3, "has left the room."),
                 )
class messageManager(models.Manager):
    
    def create_message(self, user, room, msg):
        """Create a message for the given user."""
        m = Message.objects.create(user=user,
                                   room=room,
                                   text='<strong>%s</strong> %s<br />' % (user, msg))
        return m

    def create_event(self, user, room, event_id):
        """Create an event for the given user."""
        m = Message(user=user,
                    room=room,
                    event=event_id)
        m.text = "<strong>%s</strong> <em>%s</em><br />" % (user, m.get_event_display())
        m.save()
        return m

class Message(models.Model):
    """Messages displayed in the chat client.

    Note that we have 2 categories of messages:
    - a text typed in by the user.
    - an event carried out in the room ("user X has left the room.").

    New messages should be created through the supplied manager methods, as all 
    messages get preformatted (added markup) for display in the chat window.
    For example:
    
    Messages:
    >>> user = User.objects.create_user('john', 'lennon@thebeatles.com', 'johnpassword')
    >>> room = Room.objects.create(name='Test room')
    >>> m = Message.objects.create_message(user, room, 'hello there')
    >>> m.text
    '<strong>john</strong> hello there<br />'

    Events:
    >>> m1 = Message.objects.create_event(user, room, 1)
    >>> u'<strong>john</strong> <em>has changed' in m1.text
    True

    Note that there are 2 timestamp fields:
    - a unix timestamp.
    - a datetime timestamp.
    The reason: the unix timestamp is higher performance when sending data to the browser (easier
    and faster to handle numbers instead of datetimes. The 'created' is used for displaying the date
    of messages; I could calculate it from the unix timestamp, but I'm guessing that I will get
    higher performance by storing it in the database.

    """

    user = models.ForeignKey(User, related_name='jchat_messages')
    room = models.ForeignKey(Room, help_text='This message was posted in a given chat room.')
    event = models.IntegerField(null=True, blank=True, choices=EVENT_CHOICES, help_text='An action performed in the room, either by a user or by the system (e.g. XYZ leaves room.')
    text = models.TextField(null=True, blank=True, help_text='A message, either typed in by a user or generated by the system.')
    unix_timestamp = models.FloatField(editable=False, help_text='Unix timestamp when this message was inserted into the database.')
    created = models.DateTimeField(editable=False)

    def __unicode__(self):
        return u'%s, %s' % (self.user, self.unix_timestamp)

    def save(self, **kw):
        if not self.unix_timestamp:
            self.unix_timestamp = time.time()
            self.created = datetime.datetime.fromtimestamp(self.unix_timestamp)
        super(Message, self).save(**kw)
        self.room.last_activity = int(time.time())
        self.room.save()

    class Meta:
        ordering = ['unix_timestamp']

    objects = messageManager()

def display_timestamp(t):
        """Takes a Unix timestamp as a an arg, returns a text string with
        '<unix timestamp> (<equivalent time>)'."""
        return '%s (%s)' % (t, time.strftime('%d/%m/%Y %H:%M', time.gmtime(t)))

chat/views.py
from django.http import HttpResponseBadRequest
from django.shortcuts import render_to_response, render, get_object_or_404
from django.template import RequestContext
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.utils.html import escape

from models import Room, Message

import time

# The format of the date displayed in the chat window can be customised.
try:
    DATE_FORMAT = settings.JQCHAT_DATE_FORMAT
except:
    # Use default format.
    DATE_FORMAT = "H:i:s"

# How many messages to retrieve at most.
JQCHAT_DISPLAY_COUNT = getattr(settings, 'JQCHAT_DISPLAY_COUNT', 100) 
#------------------------------------------------------------------------------
@login_required
def chat_room(request, template="jqchat/chat_rooms.html"):
    rooms = Room.objects.filter(show=True)
    return render(request, template, {'rooms':rooms})


#------------------------------------------------------------------------------
@login_required
def window(request, id, template = "jqchat/chat_test.html"):
    """A basic chat client window."""

    ThisRoom = get_object_or_404(Room, id=id)
    return render(request, template, {'room': ThisRoom})
    # return render_to_response('jqchat/chat_test.html', {'room': ThisRoom},
    #                           context_instance=RequestContext(request))

#------------------------------------------------------------------------------
@login_required
def WindowWithDescription(request, id):
    """A variant of the basic chat window, includes an updatable description to demonstrate
    how to extend the chat system."""

    ThisRoom = get_object_or_404(Room, id=id)

    return render_to_response('jqchat/chat_test_with_desc.html', {'room': ThisRoom},
                              context_instance=RequestContext(request))

#------------------------------------------------------------------------------
class Ajax(object):
    """Connections from the jQuery chat client come here.

    We receive here 2 types of calls:
    - requests for any new messages.
    - posting new user messages.

    Any new messages are always returned (even if/when posting new data).

    Requests for new messages should be sent as a GET with as arguments:
    - current UNIX system time on the server. This is used so that the server which messages have
    already been received by the client.
    On the first call, this should be set to 0, thereafter the server will supply a new system time
    on each call.
    - the room ID number.
    
    Requests that include new data for the server (e.g. new messages) should be sent as a POST and 
    contain the following extra args:
    - an action code, a short string describing the type of data sent.
    - message, a string containing the message sent by the user.

    The returned data contains a status flag:
     1: got new data.
     2: no new data, nothing to update.

    This code is written as a class, the idea being that implementations of a chat window will 
    have extra features, so these will be coded as derived classes.
    Included below is a basic example for updating the room's description field.

    """

    # Note that login_required decorators cannot be attached here if the __call__ is to be overridden.
    # Instead they have to be attached to child classes.
    def __call__(self, request, id):

        if not request.user.is_authenticated():
            return HttpResponseBadRequest('You need to be logged in to access the chat system.')
    
        StatusCode = 0 # Default status code is 0 i.e. no new data.
        self.request = request
        try:
            self.request_time = float(self.request.REQUEST['time'])
        except:
            return HttpResponseBadRequest("What's the time?")
        self.ThisRoom = Room.objects.get(id=id)
        NewDescription = None

        if self.request.method == "POST":
            print request.POST
            # User has sent new data.
            action = self.request.POST['action']
    
            if action == 'postmsg':
                msg_text = self.request.POST['message']
    
                if len(msg_text.strip()) > 0: # Ignore empty strings.
                    Message.objects.create_message(self.request.user, self.ThisRoom, escape(msg_text))
        else:
            # If a GET, make sure that no action was specified.
            if self.request.GET.get('action', None):
                return HttpResponseBadRequest('Need to POST if you want to send data.')

        # If using Pinax we can get the user's timezone.
        try:
            user_tz = self.request.user.account_set.all()[0].timezone
        except:
            user_tz = settings.TIME_ZONE
    
        # Extra JSON string to be spliced into the response.
        CustomPayload = self.ExtraHandling()
        if CustomPayload:
            StatusCode = 1
    
        # Get new messages - do this last in case the ExtraHandling has itself generated
        # new messages. 
        NewMessages = self.ThisRoom.message_set.filter(unix_timestamp__gt=self.request_time)
        if NewMessages:
            StatusCode = 1

        # Only keep the last X messages.
        l = len(NewMessages)
        if l > JQCHAT_DISPLAY_COUNT:
            NewMessages = NewMessages[l-JQCHAT_DISPLAY_COUNT:]
            
        response =  render_to_response('jqchat/chat_payload.json',
                                  {'current_unix_timestamp': time.time(),
                                   'NewMessages': NewMessages,
                                   'StatusCode': StatusCode,
                                   'NewDescription': NewDescription,
                                   'user_tz': user_tz,
                                   'CustomPayload': CustomPayload,
                                   'TimeDisplayFormat': DATE_FORMAT
                                   },
                                  context_instance=RequestContext(self.request))
        response['Content-Type'] = 'text/plain; charset=utf-8'
        response['Cache-Control'] = 'no-cache'
        return response

    def ExtraHandling(self):
        """We might want to receive/send extra data in the Ajax calls.
        This function is there to be overriden in child classes.
        
        Basic usage is to generate the JSON that then gets spliced into the main JSON 
        response.
        
        """
        return None
        

BasicAjaxHandler = Ajax()


#------------------------------------------------------------------------------
class DescriptionAjax(Ajax):
    """Example of how to handle calls with extra data (in this case, a room
    description field).
    """

    def ExtraHandling(self):
        # Check if new description sent.
        if self.request.method == "POST":
            action = self.request.POST['action']
            if action == 'change_description':
                # Note that we escape descriptions as a protection against XSS.
                self.ThisRoom.description = escape(self.request.POST['description'])
                self.ThisRoom.save()
                Message.objects.create_event(self.request.user, self.ThisRoom, 1)
        # Is there a description more recent than the timestamp sent by the client?
        # If yes, return an extra field to be tagged on to the JSON returned to the client.
        if self.ThisRoom.description and self.ThisRoom.description_modified > self.request_time:
            return ',\n        "description": "%s"' % self.ThisRoom.description
        
        return None

WindowWithDescriptionAjaxHandler = DescriptionAjax()

chat/templates/jqchat/chat_rooms.html
{% extends "admin/base_site.html" %}
{% load static %}
{% load extras_tags %}
{% block content %}

<style type="text/css">
	.chat_room_item{
		font-size: 14pt;
		padding: 8px;
		border: 1px solid #bbb;
		border-radius: 4px;
	}
	.float{
		float: left;
		width: 30%;
	}
</style>

<div>
	<h1>Salas de chat:</h1>
	<div>
		{% for room in rooms %}
			<div class="chat_room_item">
				<div class="float">
					<a href="{% url 'jqchat_test_window' room.id %}">
						{{forloop.counter}} - {{ room }}
					</a>
				</div>
				<div class="float">
					Total de mensagens:
					{{ room.message_set.all|length }}
				</div>
				<div class="float">
					Ultima mensagem:
					{{ room.last_activity|formatDate }}
				</div>
				<div style="clear:both;"></div>
			</div>
		{% empty %}
			<div class="chat_room_item">Nenhuma sala aberta no momento</div>
		{% endfor %}
	</div>
</div>

{% endblock %}

chat/templates/jqchat/chat_test.html
{% extends "admin/base_site.html" %}
{% load static %}

{# An example chat window #}

{% block head_title %}Chat Client{% endblock %}

{% block extrastyle %}{{ block.super }}
<!-- Load the JS for the chat window and start retrieving messages. -->
<script type="text/javascript" src="{% static 'js/jquery-1.10.2.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jqchat.js' %}"></script>
<script type="text/javascript">
	$(document).ready(function(){
		InitChatWindow("{% url 'jqchat_ajax' room.id %}", null);
	});
</script>
<style type="text/css">
	/* Example styling for the chat window */
   #chatwindow {
     height: 250px;
     width: 50%;
     border: 1px solid #CCC6C6;
     padding: 5px;
     margin: 10px 0;
     overflow: auto;
     background-color: white;
   }
</style>
{% endblock %}

{% block content %}

<h2>Sala: {{ room }}</h2>
<div>
  <a href="{% url 'chat' %}">Voltar Salas de chat's</a>
</div>

<div id="chatwindow"><span id="loading">Loading...</span></div>

<form id="chatform">
	{% csrf_token %}
	<label for="msg">Message:</label>
	<input type="text" id="msg" />
	<input type="submit" value="Send message" /><br />
</form>

<script type="text/javascript">document.getElementById("msg").focus();</script>

{% endblock %}

chat/templates/jqchat/chat_test_with_desc.html
{% extends "admin/base_site.html" %}
{% load static %}

{# An example chat window #}

{% block head_title %}Chat Client{% endblock %}

{% block extrastyle %}{{ block.super }}
<!-- Load the JS for the chat window and start retrieving messages. -->
<script type="text/javascript" src="{% static 'js/jquery-1.10.2.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jqchat.js' %}"></script>
<script type="text/javascript">
	$(document).ready(function(){
		InitChatWindow("{% url 'jqchat_test_window_with_description_ajax' room.id %}", HandleRoomDescription);
		// Initialise the custom code to POST new descriptions.
		InitChatDescription();
	});
</script>
<style type="text/css">
	/* Example styling for the chat window */
   #chatwindow {
     height: 250px;
     width: 400px;
     border: 1px solid;
     padding: 5px;
     margin: 10px 0;
     overflow: auto;
     background-color: white;
   }
</style>

{% endblock %}

{% block content %}
<div id="chat_left_col">
	<h1>Test Chat Client</h1>
	
	<p>This is a demo of the <a href="http://code.google.com/p/django-jqchat/">
	django-jqchat chat client</a>.</p>
	<p>This page shows how the basic chat client can be extended: the extra field
	<em>room description</em> can be updated from the client window and sent as part
	of the chat client messages. Likewise, updates to the <em>room description</em>
	elsewhere are piggybacked on to the ajax messages received from the server.</p>
	<p>For the basic client,
	<a href="{% url 'jqchat_test_window' room.id %}">see here</a>.</p>
	<p>There are 2 rooms in this demo,
	<a href="{% url 'jqchat_test_window' 1 %}">here</a> and 
	<a href="{% url 'jqchat_test_window' 2 %}">here</a>.</p>
</div>

<h2>Room name: {{ room }}</h2>
<h2>Room description: <span id="chatroom_description"></span></h2>

<div id="chatwindow"><span id="loading">Loading...</span></div>

<form id="chatform">
	<label for="msg">Message:</label>
	<input type="text" id="msg" />
	<input type="submit" value="Send message" /><br />
</form>

<form id="chatroom_description_form" method="post" action="">
	<label for="id_description">Room description:</label>
	<input id="id_description" type="text" name="description" maxlength="100" />
	<input type="submit" value="Update room description" />
</form>

<script type="text/javascript">document.getElementById("msg").focus();</script>

{% endblock %}