bolao/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'bolao_copa.views.home', name='home'),
    url(r'rank/$', 'bolao.views.listar_pontos', name='pontos'),
    url(r'jogos/$', 'bolao.views.listar_jogos', name='jogos'),
    url(r'apostas/$', 'bolao.views.gerar_aposta', name='apostas'),
    url(r'selecoes/$', 'bolao.views.listar_selecoes', name='selecoes'),
)

bolao_copa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from bolao.views import gerar_aposta, listar_pontos
from chat.views import chat_room
from django.shortcuts import redirect

def admin_index(request):
    return redirect('admin/')

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'bolao_copa.views.home', name='home'),
    url(r'^$',admin_index),
    url(r'^bolao/', include('bolao.urls')),
    url(r'^chat/', include('chat.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

def get_admin_urls(urls):
    def get_urls():
        my_urls = patterns('',
            (r'^apostas/$', admin.site.admin_view(gerar_aposta)),
            (r'^ranking/$', admin.site.admin_view(listar_pontos)),
            (r'^chat/$', admin.site.admin_view(chat_room)),
        )
        return my_urls + urls
    return get_urls

admin_urls = get_admin_urls(admin.site.get_urls())
admin.site.get_urls = admin_urls

chat/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    # Example chat room.
    url(r"room/$", views.chat_room, name="chat"),
    url(r"room/(?P<id>\d+)/$", views.window, name="jqchat_test_window"),
    url(r"room/(?P<id>\d+)/ajax/$", views.BasicAjaxHandler, name="jqchat_ajax"),
    # Second example room - adds room descriptions.
    url(r"room_with_description/(?P<id>\d+)/$", views.WindowWithDescription, name="jqchat_test_window_with_description"),
    url(r"room_with_description/(?P<id>\d+)/ajax/$", views.WindowWithDescriptionAjaxHandler, name="jqchat_test_window_with_description_ajax"),
)

bolao/models.py
# coding: utf-8

from django.db import models
from django.conf import settings

class Selecao(models.Model):
	nome = models.CharField(
		max_length=50,verbose_name=u'Nome',
		unique=True, null=False)
	img = models.URLField(verbose_name=u'Link Imagem')

	def __unicode__(self):
		return "%s"%self.nome

	class Meta:
		verbose_name = u'Seleção'
		verbose_name_plural = u'Seleções'

class Grupo(models.Model):
	nome = models.CharField(
		max_length=50,verbose_name=u'Nome',
		unique=False, null=False)
	exibir = models.BooleanField(verbose_name=u'Exibir',default=True)

	def __unicode__(self):
		return self.nome

	class Meta:
		ordering=['nome']


class Jogo(models.Model):
	time_a = models.ForeignKey('Selecao', related_name='time_a',
	 verbose_name=u'Time A', null=False, blank=False)
	time_b = models.ForeignKey('Selecao', related_name='time_b',
		verbose_name=u'Time B', null=False, blank=False)
#	resultado = models.OneToOneField(Resultado,
#		verbose_name=u'Resultado', null=True, blank=True)
	grupo = models.ForeignKey('Grupo',
		verbose_name=u'Grupo', null=False, blank=False)

	def __unicode__(self):
		return "%s - %s X %s"%(
			self.grupo.nome,
			self.time_a.nome,
			self.time_b.nome)

	class Meta:
		ordering=['grupo','time_a']

class Pontuacao(models.Model):
	usuario = models.ForeignKey(settings.AUTH_USER_MODEL, null=False)
	#usuario = models.OneToOneField(settings.AUTH_USER_MODEL, null=False)
	pontos = models.IntegerField()	

	def __unicode__(self):
		return "%s --> %d pts"%(self.usuario, self.pontos)

	class Meta:
		ordering = ['usuario']
		verbose_name = u'Pontuação'
		verbose_name_plural = u'Pontuações'


class Placar(models.Model):
	gols_time_a = models.PositiveIntegerField(
		verbose_name=u'Resultado Time A', default=0)
	gols_time_b = models.PositiveIntegerField(
		verbose_name=u'Resultado Time B', default=0)
	jogo = models.ForeignKey('Jogo', null=False, blank=False)

	def __unicode__(self):
		return "%s - %s  (%d) X %s  (%d)"%(
			self.jogo.grupo,
			self.jogo.time_a.nome,
			self.gols_time_a,
			self.jogo.time_b.nome,
			self.gols_time_b)

	class Meta:
		ordering = ['jogo']

class Resultado(Placar):
	vencedor = models.CharField(
		max_length=60,verbose_name='Vencedor',
		blank=True,default='------')

	def __unicode__(self):
		return "%s - %s  (%d) X %s  (%d) : Vencedor: %s"%(
			self.jogo.grupo,
			self.jogo.time_a.nome,
			self.gols_time_a,
			self.jogo.time_b.nome,
			self.gols_time_b, 
			self.vencedor)

	class Meta:
		verbose_name = u'Resultado'
		verbose_name_plural = u'Resultados'

class Aposta(Placar):
	usuario = models.ForeignKey(settings.AUTH_USER_MODEL)

	def __unicode__(self):
		return "%s --> %s "%(self.usuario, super(Aposta, self).__unicode__())

	def get_absolute_url(self):
		return '/admin/aposta/'

	class Meta:
		ordering = ['usuario','jogo']
		permissions = (
			('gerar_aposta', 'Poder visualizar e gerar aposta'),
			)

bolao/forms.py
#!/usr/bin/env python
from django import forms
from django.forms.models import inlineformset_factory

from models import Aposta


class ApostaForm(forms.ModelForm):

    class Meta:
        model = Aposta
        #fields = ['website', 'enterprise']


# class SocialForm(forms.ModelForm):
#     TYPE_CHOICES = [(x.id, x.name) for x in TypeSocial.objects.all()]

#     url = forms.URLField(required=False)
#     type_social = forms.ChoiceField(
#         choices=TYPE_CHOICES, required=False)

#     class Meta:
#         model = Social
#         fields = ['url', 'type_social']

#     def clean(self):
#         self._validade_unique = True
#         id = self.cleaned_data.get('type_social')
#         self.cleaned_data['type_social'] = TypeSocial.objects.get(pk=id)

#         return self.cleaned_data


# SocialFormset = inlineformset_factory(
#     Member, Social,
#     form=SocialForm,
#     can_delete=False,
# )

bolao/views.py
from django.shortcuts import render
from django.http import HttpResponse
from models import Selecao, Grupo, Jogo, Pontuacao, Aposta
from django.contrib.auth.decorators import login_required
import re
from forms import ApostaForm

@login_required
def listar_selecoes(request, template='selecoes.html'):
	times = Selecao.objects.all()
	return render(request, template, {'selecoes':times})

@login_required
def listar_jogos(request, template='jogos.html'):
	grupos = Grupo.objects.filter(exibir=True)
	jogos = Jogo.objects.all()
	return render(request, template, {'grupos':grupos, 'jogos':jogos})

@login_required
def listar_pontos(request, template='ranking.html'):
	pontos = Pontuacao.objects.order_by('-pontos')
	return render(request, template, {'pontos':pontos})

@login_required
def gerar_aposta(request, template='apostas.html'):
	user = request.user
	if user.id != None:
		if request.method == "POST":
			apostas_itens = _process_post(request)
			for ap in apostas_itens.values():
				ap.save()
			return HttpResponse('Apostas Salvas com sucesso!')
			
		apostas = {}
		grupos = Grupo.objects.filter(exibir=True)
		jogos = [jg[0] for jg in Jogo.objects.values_list('id')]
		apostas = []
		for jg_id in jogos:
			ap = Aposta.objects.get_or_create(usuario_id = user.id, jogo_id=jg_id)
			apostas.append(ApostaForm(instance=ap[0]))

		context = {
			'grupos':grupos,
			'form':apostas,
		}
		return render(request, template,context)
	return HttpResponse('E necessario logar para visualizar')

@login_required
def _process_post(request):
	apostas = {}
	for key,item  in request.POST.items():
		id = re.sub('[^\d]', '', key)
		if id != '':
			if not apostas.has_key(id):
				apostas[id] = Aposta(usuario_id=request.user.id)
			attr = re.sub('[\d\[\]]', '', key)
			apostas[id].__setattr__(attr, int(item))
	return apostas

from django.views.generic.list import ListView
from django.views.generic.edit import CreateView

class GerarAposta(CreateView):
	model = Aposta
	template_name = 'apostas.html'
	success_url = '/'

	def get_context_data(self, **kargs):
		context = super(GerarAposta, self).get_context_data(**kargs)
		user = context.get('user')
		context['grupos'] = Grupo.objects.all()
		context['apostas'] = Aposta.objects.get(usuario_id = user.id)
		return context

	def form_valid(self, form):
		aposta = form.save(commit=False)
		aposta.usuario = self.request.user
		aposta.save()
		return super(GerarAposta, self).form_valid(self, form)

	def post(self, request, **kargs):
		apostas = self.process_post(request)
		for e in apostas.values():
			print e.save()
		return HttpResponse('Apostas Realizadas')

	def process_post(self, request):
		apostas = {}
		for key,item  in request.POST.items():
			id = re.sub('[^\d]', '', key)
			if id != '':
				if not apostas.has_key(id):
					apostas[id] = Aposta()
					apostas[id].usuario_id = request.user.id
				attr = re.sub('[\d\[\]]', '', key)
				apostas[id].__setattr__(attr, int(item))
		return apostas

bolao/templates/apostas.html
{% extends 'admin/base_site.html' %}
{% load static %}
{% block content %}
<script type="text/javascript" src="{% static 'js/jquery-1.10.2.js' %}"></script>
<link type="text/css" rel="stylesheet" href="{% static 'admin/css/forms.css' %}"></link>

<style type="text/css">
	.item_grupo{
		margin: 5px 10px;
		padding: 5px;
		border: 1px solid #CCC;
		position: relative;
	}
	.nome_grupo{
		text-align: center;
		font-size: 18pt; 
	}
	.item_jogo{
		text-align: center;
		font-size: 14pt; 	
		float: left;
		width: 48%;
		height: 35px;
		border: 1px solid #DDD;
		border-radius: 3px;
		margin: 5px;
		padding-top: 7px;
	}
	.cl{
		clear: both;
	}
	.detalhe_jogo{
		margin: 0px 45px;
		height: 38px;
		width: auto;
	}
	.time_a{
		float: left;
	}
	.time_b{
		float: right;
	}

	input[type="number"]{
		text-align: center;
		width: 50px;
	}
</style>
<div class="grupos">
	{% for grp in grupos %}
		<div class="item_grupo">
			<div class="nome_grupo">{{ grp.nome }}</div>
			{% for jg in grp.jogo_set.all %}
				<div class="item_jogo">
					<input class="jogo_id" id="id_jogo_{{ jg.id }}" 
					name="jogo" type="hidden" value="{{ jg.id }}" />
					{% for ap in form %}
						{% if ap.initial.jogo == jg.id %}
							<input class="id" id="id_{{ ap.id }}" 
							name="id" type="hidden" value="{{ ap.initial.id }}" />
							<div class="detalhe_jogo time_a">
								{{ ap.gols_time_a }}
							</div>
							<div class="time_a">
								<img src="{{ jg.time_a.img }}">
							</div>
								{{ jg.time_a }}
							 X 
								{{ jg.time_b }}
							<div class="detalhe_jogo time_b">
								{{ ap.gols_time_b }}
							</div>
							<div class="time_b">
								<img src="{{ jg.time_b.img }}">
							</div>
						{% endif %}
					{% endfor %}
					<div class="cl"></div>
				</div>
			{% endfor %}
			<div class="cl"></div>
		</div>
	{% endfor %}
</div>
<div class="submit-row">
	<input class="btn_enviar default" type="button" value="Salvar Apostas"></input>
</div>

<script type="text/javascript">
	var data = {}
	data['csrfmiddlewaretoken'] = '{{ csrf_token }}';
	$(".btn_enviar").click(function(){
		//data = [];
		$(".item_jogo").each(function(index){
			var id = $(this).children(".id").val();
			item = {}
			item.id = id;
			item.jogo_id = $(this).children(".jogo_id").val();
			item.gols_time_a = $(this).children(".time_a").children().val();
			item.gols_time_b = $(this).children(".time_b").children().val();
			data[id] = item;
		});
		enviar(data);
	});

	function enviar(data){
		$.ajax({
			url:'/bolao/apostas/',
			//dataType:'json',
			data:data,
			method:'post',
			success:function(result){
				alert(result);
			},
			error:function(result) {
				alert(result);
			}
		});
	}
</script>

{% endblock %}

bolao/templates/gerar_apostas.html
{% load static %}
<html>
<head>
	<script type="text/javascript" src="{% static 'js/jquery-1.10.2.js' %}"></script>
	<style type="text/css">
		.item_grupo{
			margin: 5px 10px;
			padding: 5px;
			border: 1px solid #CCC;
			position: relative;
		}
		.nome_grupo{
			text-align: center;
			font-size: 18pt; 
		}
		.item_jogo{
			text-align: center;
			font-size: 14pt; 	
			float: left;
			width: 48%;
			height: 35px;
			border: 1px solid #DDD;
			border-radius: 3px;
			margin: 5px;
			padding-top: 7px;
		}
		.cl{
			clear: both;
		}
		.detalhe_jogo{
			margin: 0px 45px;
			height: 38px;
			width: auto;
		}
		.time_a{
			float: left;
		}
		.time_b{
			float: right;
		}

		input[type="number"]{
			text-align: center;
			width: 50px;
		}
	</style>
</head>
<body>
	<div>

	</div>
	<div class="grupos">
		{% for grp in grupos %}
			<div class="item_grupo">
				<div class="nome_grupo">{{ grp.nome }}</div>
				{% for jg in grp.jogo_set.all %}
					<div class="item_jogo">
						<input class="jogo_id" id="id_jogo_{{ jg.id }}" 
						name="jogo" type="hidden" value="{{ jg.id }}" />
						<input class="jogo_id" id="id_jogo_{{ jg.id }}" 
						name="jogo" type="hidden" value="{{ jg.id }}" />
						<div class="detalhe_jogo time_a">
							{{ form[jg.id].gols_time_a }}
						</div>
						{{ jg.time_a }} X {{ jg.time_b }}
						<div class="detalhe_jogo time_b">
							{{ form[jg.id].gols_time_b }}
						</div>
						<div class="cl"></div>
					</div>
				{% endfor %}
				<div class="cl"></div>
			</div>
		{% endfor %}
	</div>
	<div>
		<button class="btn_enviar">Testar</button>
	</div>
</body>
<script type="text/javascript">
	var data = {}
	data['csrfmiddlewaretoken'] = '{{ csrf_token }}';
	$(".btn_enviar").click(function(){
		//data = [];
		$(".item_jogo").each(function(index){
			var id = $(this).children(".jogo_id").val();
			item = {}
			item.jogo_id = $(this).children(".jogo_id").val();
			item.gols_time_a = $(this).children(".time_a").children().val();
			item.gols_time_b = $(this).children(".time_b").children().val();
			data[id] = item;
		});
		enviar(data);
	});

	function enviar(data){
		$.ajax({
			url:'/bolao/apostas/',
			dataType:'json',
			data:data,
			method:'post',
			success:function(result){
				alert(result);
			},
			error:function(result) {
				alert(result);
			}
		});
	}
</script>
</html>

bolao/templates/jogos.html
<html>
<head>
	<style type="text/css">
		.item_grupo{
			margin: 5px 10px;
			padding: 5px;
			border: 1px solid #CCC;
			position: relative;
		}
		.nome_grupo{
			text-align: center;
			font-size: 18pt; 
		}
		.item_jogo{
			text-align: center;
			font-size: 14pt; 	
			float: left;
			width: 48%;
			border: 1px solid #DDD;
			border-radius: 3px;
			margin: 5px;
		}
		.cl{
			clear: both;
		}
	</style>
</head>
<body>
	<div class="grupos">
		{% for grp in grupos %}
			<div class="item_grupo">
				<div class="nome_grupo">{{ grp.nome }}</div>
				{% for jg in grp.jogo_set.all %}
					<div class="item_jogo">
						{{ jg.time_a }} X {{ jg.time_b }}
					</div>
				{% endfor %}
				<div class="cl"></div>
			</div>
		{% endfor %}
	</div>
</body>
</html>

bolao/templates/jogos_sem_aposta.html
{% for jg in object_list %}
	{{ jg.time_a }} X {{ jg.time_b }}
	<br />
{% endfor %}

bolao/templates/ranking.html
{% extends 'admin/base_site.html' %}
{% load static %}
{% block content %}
	<style type="text/css">
	.rank{
		margin: 15px;
	}
	.item_pontuacao{
		margin: 5px;
		font-size: 14pt;
		padding: 8px 22px;
		border: 1px solid #DDD;
		border-radius: 3px; 
	}
	</style>

	<div class="rank">
		<h1> Ranking </h1>
		{% for item  in pontos %}
			<div class="item_pontuacao">
				( {{ forloop.counter }} ) {{ item }}
			</div>
		{% empty %}
			<div>
				Nenhum usuário pontuou ainda.
			</div>
		{% endfor %}
	</div>
{% endblock %}

bolao/templates/selecoes.html
<html>
<head>
	<style type="text/css">
	.item_selecao{
		font-size: 18pt;
		margin: 10px 15px;
		position: relative;
		width: 45%;
		float: left;
	}
	.nome_selecao{
		float: left;
	}
	.img_selecao{
		float: right;
		padding-right: 10px;
	}
	</style>
</head>
<body>
<div class="times">
	{% for item in selecoes %}
		<div class='item_selecao'>
			<div class="nome_selecao">
				{{ item.nome }}
			</div>
			<div class="img_selecao">
				<img class="imagem_bandeira" src="{{ item.img }}" />
			</div>
		</div>
	{% empty %}
		<div>
			Nenhuma Seleção Cadastrada
		</div>
	{% endfor %}
</div>
</body>
</html>